server:
  error:
    whitelabel:
      enabled: false
spring:
 devtools:
  livereload:
   enabled: true
 thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
 task:
  execution:
   pool:
    core-size: 8
    max-size: 8
 jackson:    serialization:
     FAIL_ON_EMPTY_BEANS: false    visibility:
     field: any mongodb:    embedded:      storage:        database-dir: mongodb
 data:
  mongodb:
   authentication-database: admin
   database: test_db
   port: 27017
   host: localhost 
      
logging:
  exception-conversion-word: "%wEx"
  register-shutdown-hook: true
  level:
    com.amazonaws: error
    com.anthunt.aws.network: info
    org.springframework: info
    org.springframework.boot.autoconfigure.mongo: error